
site_name: 笔记仓库
theme:
  name: material
  custom_dir: overrides
  logo: logo.png
  favicon: assets/images/favicon.png
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.expand
    - navigation.tracking
    - navigation.path
    - navigation.footer
    - navigation.top
    - navigation.indexes
    - toc.follow
    - navigation.prune 
    - header.autohide
    - content.code.copy
    - content.code.select

  palette:    
    - media: "(prefers-color-scheme dark)"
      scheme: slate
      primary: blue
      accent: cyan 
      toggle:
        icon: material/brightness-7
        name: 开启日间模式

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: 开启夜间模式

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RoureYungLoo
      name: RoureYungLoo
    - icon: fontawesome/solid/paper-plane
      link: mailto:<luruoyang@petalmail.com>
      name: 禄若阳的花瓣邮箱
  analytics:
    provider: google
    property: G-Q4DFFNKQER
  feedback:
      title: 这个页面有用吗？
      ratings:
        - icon: material/emoticon-happy-outline
          name: 这个页面有用
          data: 1
          note: >-
            谢谢~
        - icon: material/emoticon-sad-outline
          name: 这个页面有待改进
          data: 0
          note: >-
            感谢你的反馈！

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - pymdownx.snippets
  - attr_list
  - toc: 
      permalink: true
      toc_depth: 6
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      auto_title: true
      linenums: true
      linenums_style: inline  pymdownx-inline
      line_spans: __span
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.keys
  - pymdownx.tabbed
  - def_list
  
